
# This workflow will build, test and deploy the application
name: Heroku CI/CD

on:
  push:
    branches: [ master ]

jobs:
  # Deploy
  deploy:
    #needs: build-test
    runs-on: ubuntu-latest
    
    # Steps
    steps:
      - name: Update remote
        run: heroku git:remote -a $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: master
